#!/usr/bin/env python3
"""Generate lib/locations-data.json with unique copy per city (SEO)."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "lib" / "locations-data.json"


def job(service: str, suburb: str, time_ago: str, note: str) -> dict:
    return {
        "service": service,
        "suburb": suburb,
        "timeAgo": time_ago,
        "note": note,
    }


def faq(q: str, a: str) -> dict:
    return {"q": q, "a": a}


# fmt: off
GAUTENG = [
    {
        "slug": "johannesburg",
        "name": "Johannesburg",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Joburg's fastest locksmith service",
        "description": "From the CBD grid to Melville and Braamfontein, we route emergency locksmiths who know inner-city complexes, student digs, and office blocks — not generic call-centre scripts.",
        "suburbs": ["Johannesburg CBD", "Rosebank", "Parktown", "Braamfontein", "Melville", "Auckland Park", "Westdene", "Fordsburg"],
        "nearbyAreas": ["Sandton", "Randburg", "Soweto", "Roodepoort"],
        "recentJobs": [
            job("Car unlock", "Rosebank", "14 min response", "Keys left in boot at office park — opened without damage"),
            job("House lockout", "Melville", "18 min response", "Tenant back from dinner, cylinder turned stiff"),
            job("Lock replacement", "Parktown", "Same day", "Victorian home — upgraded mortice after break-in scare"),
        ],
        "faqs": [
            faq("What does a locksmith typically charge in Johannesburg?", "Rates depend on time, distance, and parts. You should get an upfront scope before drilling — especially in the CBD where parking and access add time."),
            faq("How fast can someone reach Rosebank or Parktown?", "We aim for minutes, not hours. Emergencies jump the queue; exact ETA depends on traffic and who is nearest when you call."),
            faq("Do you work after midnight in Joburg CBD?", "Yes. Lockouts do not keep office hours — our network is structured for late-night CBD and inner-ring suburbs."),
            faq("Is Melville or Braamfontein covered?", "Yes — including student-heavy blocks where verification and access rules matter."),
        ],
    },
    {
        "slug": "sandton",
        "name": "Sandton",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Premium locksmith service in Sandton",
        "description": "Sandton City, Rivonia Road and estate clusters mean high-security vehicles and access control — we match locksmiths used to malls, office towers, and gated complexes.",
        "suburbs": ["Sandton CBD", "Rivonia", "Bryanston", "Morningside", "Sunninghill", "Paulshof", "Woodmead", "Linden"],
        "nearbyAreas": ["Midrand", "Randburg", "Fourways", "Johannesburg"],
        "recentJobs": [
            job("Car lockout", "Sandton City", "11 min response", "BMW — keys visible on passenger seat; opened at mall basement"),
            job("Lost car key", "Rivonia", "27 min response", "Spare coded on-site after wallet stolen at lunch spot"),
            job("House lockout", "Bryanston", "16 min response", "Estate visitor gate — intercom linked to deadbolt"),
        ],
        "faqs": [
            faq("Is there a 24 hour locksmith in Sandton who knows estates?", "Yes. Many jobs are Bryanston or Morningside estates — mention the estate name when you request help."),
            faq("How much should I expect to pay near Sandton City?", "Mall parking and peak-hour traffic can add time on site. Get a written or verbal scope before work starts."),
            faq("Can you programme keys for premium cars in Sandton?", "Many locksmiths on the network handle common luxury brands — describe the vehicle when booking."),
            faq("Do you cover Rivonia office parks after hours?", "Yes — including late exits when access cards fail."),
        ],
    },
    {
        "slug": "pretoria",
        "name": "Pretoria",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "24/7 locksmith services in Pretoria",
        "description": "Hatfield, Menlyn and the government precinct bring a mix of students, embassies, and family homes — we dispatch pros who know Tshwane traffic and campus-adjacent complexes.",
        "suburbs": ["Pretoria CBD", "Menlyn", "Hatfield", "Brooklyn", "Arcadia", "Sunnyside", "Silverton", "Garsfontein"],
        "nearbyAreas": ["Centurion", "Midrand", "Mamelodi", "Atteridgeville"],
        "recentJobs": [
            job("House lockout", "Hatfield", "19 min response", "UP student — keys inside shared flat near campus"),
            job("Lock upgrade", "Brooklyn", "Same day", "Post-burglary — new cylinder + striker plate"),
            job("Car unlock", "Menlyn", "13 min response", "Keys in ignition at rooftop parking"),
        ],
        "faqs": [
            faq("Are locksmith prices different in Pretoria than in Joburg?", "Broadly similar, but travel across Tshwane and estate access can shift the total. Always confirm scope first."),
            faq("Do you cover Arcadia and Sunnyside flats?", "Yes — including blocks with multiple units and shared entrances."),
            faq("Can you help near the Union Buildings or embassies?", "Often yes — bring ID; some sites have extra security checks."),
            faq("Is Hatfield covered at night during term time?", "Yes — we regularly assist students and landlords after hours."),
        ],
    },
    {
        "slug": "midrand",
        "name": "Midrand",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Midrand locksmith — halfway between JHB and PTA",
        "description": "Halfway House, Kyalami and Carlswald sit between two metros — ideal for fast routing, but estate rules and mall parking still matter for every job.",
        "suburbs": ["Midrand", "Halfway House", "Kyalami", "Vorna Valley", "Carlswald", "Grand Central"],
        "nearbyAreas": ["Sandton", "Centurion", "Fourways", "Kempton Park"],
        "recentJobs": [
            job("Car lockout", "Halfway House", "15 min response", "Keys locked at Boulders — shopper with toddler in tow"),
            job("Gate motor", "Kyalami", "Same day", "Estate gate stuck — manual release then motor service referral"),
            job("Lock replacement", "Vorna Valley", "2 hours", "New tenants — full cylinder swap on sectional title"),
        ],
        "faqs": [
            faq("Is Midrand slower because it is 'between' cities?", "Not necessarily — we match the nearest available locksmith from the Sandton, Centurion, or East Rand side depending on traffic."),
            faq("Do you work on Kyalami estates with strict access lists?", "Yes — name the estate and gate when requesting; arrival may need security clearance."),
            faq("Can you reach Grand Central business park quickly?", "Often within our target window — peak N1/N3 traffic is the main variable."),
            faq("What if I am locked out at Waterfall or similar new developments?", "Describe the estate — many use standard cylinders; some need specialist hardware."),
        ],
    },
    {
        "slug": "centurion",
        "name": "Centurion",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Fast locksmith service in Centurion",
        "description": "Irene, Lyttelton and Centurion Mall bring family homes and small businesses — we focus on clear quotes before drilling patio doors or office glass.",
        "suburbs": ["Centurion CBD", "Irene", "Lyttelton", "Hennopspark", "Eldoraigne", "Wierda Park"],
        "nearbyAreas": ["Pretoria", "Midrand", "Atteridgeville"],
        "recentJobs": [
            job("House lockout", "Irene", "17 min response", "Child inside — priority dispatch to secure entry"),
            job("Car unlock", "Centurion CBD", "12 min response", "Near mall — transponder misread after battery flat"),
            job("Lock upgrade", "Lyttelton", "Same day", "Deadbolt added after attempted kick-in"),
        ],
        "faqs": [
            faq("How much does a locksmith cost in Centurion for a house lockout?", "Expect a call-out plus labour; parts extra if the cylinder must be replaced. Ask for the full picture before approval."),
            faq("Do you cover Irene farms and smallholdings?", "Yes — longer driveways can add a few minutes to ETA."),
            faq("Are you available near Centurion Mall on Sundays?", "Yes — weekends are common for shopping-centre car lockouts."),
            faq("Can you help with access control at office parks in Highveld?", "Many jobs are standard locks; some need a specialist — describe the system."),
        ],
    },
    {
        "slug": "randburg",
        "name": "Randburg",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Randburg locksmith available 24/7",
        "description": "Ferndale, Northcliff and Cresta mix freestanding houses with townhouse complexes — we match locksmiths who know boom gates and shared driveways.",
        "suburbs": ["Randburg", "Ferndale", "Northcliff", "Bordeaux", "Robindale", "Cresta"],
        "nearbyAreas": ["Sandton", "Fourways", "Roodepoort", "Johannesburg"],
        "recentJobs": [
            job("Car lockout", "Ferndale", "14 min response", "Bakkie — keys in tray at hardware run"),
            job("House lockout", "Northcliff", "20 min response", "Early morning — side gate padlock seized"),
            job("Key duplication", "Cresta", "Same day", "Spare keys for elderly parent"),
        ],
        "faqs": [
            faq("Is there a locksmith in Randburg available on public holidays?", "Yes — holidays are peak for braai-day lockouts and visiting family."),
            faq("How fast can someone reach Ferndale or Robindale?", "Usually within our metro target; rain and peak traffic on Beyers Naude can add delay."),
            faq("Do you cover Cresta Mall parking issues?", "Yes — car lockouts near major retail are common."),
            faq("Can you replace garage-door locks in Randburg?", "Often — describe whether it is a manual door or motorised system."),
        ],
    },
    {
        "slug": "roodepoort",
        "name": "Roodepoort",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Roodepoort locksmith — west of Johannesburg",
        "description": "Florida, Constantia Kloof and Little Falls blend older homes with newer clusters — rusted gate hardware and weathered front cylinders are everyday fixes here.",
        "suburbs": ["Roodepoort", "Florida", "Constantia Kloof", "Horizon", "Wilgeheuwel", "Little Falls"],
        "nearbyAreas": ["Johannesburg", "Soweto", "Krugersdorp", "Randburg"],
        "recentJobs": [
            job("House lockout", "Constantia Kloof", "22 min response", "Weekend — sliding door track jammed shut"),
            job("Lock replacement", "Florida", "Same day", "Rusted rim lock on cottage — upgraded to cylinder"),
            job("Car unlock", "Wilgeheuwel", "18 min response", "Shopping centre — remote battery died mid-shop"),
        ],
        "faqs": [
            faq("Do locksmiths in Roodepoort charge less than Sandton?", "Often slightly lower attendance, but the job type matters more than the suburb name."),
            faq("How long to reach Little Falls or Honeydew-adjacent areas?", "Distance and ridge roads can add minutes — share a pinned location."),
            faq("Are you available after hours in Florida?", "Yes — night-time home lockouts are common."),
            faq("Can you fix gate locks at West Rand complexes?", "Yes — mention single vs double gate and motor type."),
        ],
    },
    {
        "slug": "soweto",
        "name": "Soweto",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Locksmith services in Soweto",
        "description": "Diepkloof, Meadowlands and Orlando need locksmiths who respect community context — we focus on clear pricing and fast, respectful service.",
        "suburbs": ["Soweto", "Diepkloof", "Meadowlands", "Orlando", "Dobsonville", "Protea Glen"],
        "nearbyAreas": ["Johannesburg", "Roodepoort", "Lenasia"],
        "recentJobs": [
            job("House lockout", "Diepkloof", "20 min response", "Evening — keys misplaced after taxi home"),
            job("Lock replacement", "Orlando", "Same day", "New tenant move-in — full rekey"),
            job("Car unlock", "Protea Glen", "24 min response", "Toyota — keys on seat at spaza stop"),
        ],
        "faqs": [
            faq("How fast can a locksmith reach Soweto from request?", "We dispatch the nearest verified pro — ETA depends on where they are when you call."),
            faq("Are night call-outs safe for residents?", "Use a known platform; verify ID. Vula24 only routes verified locksmiths."),
            faq("Do you cover Protea Glen and Dobsonville?", "Yes — list your street and landmark when booking."),
            faq("What if I cannot afford premium hardware?", "Ask for repair-first options where the lock allows."),
        ],
    },
    {
        "slug": "boksburg",
        "name": "Boksburg",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Boksburg locksmith — East Rand",
        "description": "East Rand Mall, Dawn Park and industrial strips mean a mix of retail lockouts and family homes — we route locksmiths who know the R21 corridor.",
        "suburbs": ["Boksburg", "Benoni", "Brakpan", "Dawn Park", "Boksburg North"],
        "nearbyAreas": ["Germiston", "Kempton Park", "Alberton"],
        "recentJobs": [
            job("Car lockout", "Boksburg", "16 min response", "East Rand Mall — keys in hatch loading groceries"),
            job("House lockout", "Dawn Park", "21 min response", "Evening shift worker — mortice stuck"),
            job("Lock repair", "Benoni", "Same day", "Shopfront latch failed after attempted break-in"),
        ],
        "faqs": [
            faq("Is there a locksmith near East Rand Mall?", "Yes — mall parking lockouts are common; share level and pillar."),
            faq("Do Benoni and Brakpan fall under the same routing?", "Usually the same East Rand pool — ETA depends on who is free."),
            faq("How much for a car unlock in Boksburg after 10pm?", "After-hours rates may apply — confirm before work."),
            faq("Can you help at industrial sites in Boksburg North?", "Often — describe roller-shutter vs standard door."),
        ],
    },
    {
        "slug": "germiston",
        "name": "Germiston",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Germiston locksmith services",
        "description": "Edenvale, Bedfordview and Primrose blend dense retail with gated residential — Eastgate traffic and loading zones shape how we plan every dispatch.",
        "suburbs": ["Germiston", "Edenvale", "Bedfordview", "Lambton", "Primrose"],
        "nearbyAreas": ["Johannesburg", "Boksburg", "Alberton"],
        "recentJobs": [
            job("Car unlock", "Edenvale", "13 min response", "Near Eastgate — keys locked with engine running"),
            job("Lock replacement", "Bedfordview", "Same day", "High-security cylinder after attempted break-in"),
            job("House lockout", "Germiston", "19 min response", "Late evening — cylinder turned, key sheared"),
        ],
        "faqs": [
            faq("Can you reach Edenvale quickly during peak Eastgate traffic?", "We factor traffic — share if you are at the mall vs a quiet street."),
            faq("Do Bedfordview estates need extra verification?", "Sometimes — have ID ready for complex access."),
            faq("Are Germiston industrial workshops covered?", "Yes — describe roller door vs personnel door."),
            faq("What does a night unlock cost near the N12?", "Depends on time and job — always confirm scope first."),
        ],
    },
    {
        "slug": "fourways",
        "name": "Fourways",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Fourways locksmith — northern Johannesburg",
        "description": "Fourways Mall, Lonehill and Dainfern estates mean intercoms, biometrics, and high-spec cars — we match locksmiths comfortable with modern access gear.",
        "suburbs": ["Fourways", "Lonehill", "Douglasdale", "Dainfern", "Broadacres", "Chartwell"],
        "nearbyAreas": ["Sandton", "Randburg", "Midrand", "Bryanston"],
        "recentJobs": [
            job("Car lockout", "Fourways", "12 min response", "Fourways Mall basement — VW with keys on seat"),
            job("House lockout", "Lonehill", "17 min response", "Estate — visitor pass expired, gate locked"),
            job("Access control", "Dainfern", "Same day", "Intercom fault after power dip"),
        ],
        "faqs": [
            faq("Do Fourways estates need the locksmith pre-authorised?", "Often yes — give security a heads-up when you book."),
            faq("Can you open cars near Fourways Crossing at night?", "Yes — describe parking section for faster find."),
            faq("Are smart locks common in Lonehill?", "Increasingly — say brand and error code if the app failed."),
            faq("How much is a typical house lockout in Chartwell?", "Varies by lock type — mortice vs cylinder changes the job."),
        ],
    },
    {
        "slug": "kempton-park",
        "name": "Kempton Park",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Kempton Park locksmith near OR Tambo",
        "description": "Airport hotels, logistics parks and Birchleigh suburbs mean odd-hour call-outs — we route locksmiths who know OR Tambo pick-up chaos and estate boom gates.",
        "suburbs": ["Kempton Park", "Birchleigh", "Norkem Park", "Pomona", "Bredell", "Edleen"],
        "nearbyAreas": ["Boksburg", "Edenvale", "Tembisa", "Benoni"],
        "recentJobs": [
            job("Car unlock", "Kempton Park", "14 min response", "Rental return lane — keys in boot at long-stay parking"),
            job("Lost car key", "Birchleigh", "31 min response", "New key coded — wallet left on plane"),
            job("House lockout", "Norkem Park", "20 min response", "Night shift — deadbolt jammed after humidity"),
        ],
        "faqs": [
            faq("Is there a locksmith near OR Tambo for tourists?", "Yes — describe terminal area; airport traffic affects ETA."),
            faq("Do airport-area hotels use the same locksmiths?", "Often — mention hotel name and room tower."),
            faq("How much extra is a 2am call-out in Kempton?", "After-hours premiums vary — confirm before work."),
            faq("Can you help with fleet vans locked at logistics parks?", "Yes — describe loading bay access."),
        ],
    },
    {
        "slug": "alberton",
        "name": "Alberton",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Alberton locksmith — South Rand",
        "description": "Brackenhurst, Meyersdal and Alberton City blend family estates with retail strips — we handle everything from patio sliders to mall parking lockouts.",
        "suburbs": ["Alberton", "Brackenhurst", "New Redruth", "Meyersdal", "Verwoerdpark"],
        "nearbyAreas": ["Germiston", "Boksburg", "Johannesburg South"],
        "recentJobs": [
            job("House lockout", "Brackenhurst", "19 min response", "Keys left inside — dogs audible, fast entry priority"),
            job("Lock replacement", "Meyersdal", "Same day", "Estate home — upgrade after attempted crowbar entry"),
            job("Car unlock", "Alberton", "15 min response", "Alberton City — keys in ignition at undercover parking"),
        ],
        "faqs": [
            faq("Are Alberton prices similar to Germiston?", "Usually in the same band — job complexity matters more."),
            faq("Do you cover Meyersdal ridge homes?", "Yes — steep driveways can affect where the van parks."),
            faq("Can you rekey after tenant change in Verwoerdpark?", "Yes — ask for full rekey vs single cylinder."),
            faq("Is Sunday service available in Alberton?", "Yes — weekends are busy for family lockouts."),
        ],
    },
    {
        "slug": "benoni",
        "name": "Benoni",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Benoni locksmith — East Rand",
        "description": "Northmead, Rynfield and Daveyton cover a wide spread — we focus on honest ETAs across the East Rand so you are not left guessing.",
        "suburbs": ["Benoni", "Daveyton", "Rynfield", "Northmead", "Lakefield", "Crystal Park"],
        "nearbyAreas": ["Boksburg", "Kempton Park", "Springs"],
        "recentJobs": [
            job("Car lockout", "Northmead", "16 min response", "Northmead Square — keys visible on dash"),
            job("House lockout", "Rynfield", "22 min response", "Sunday morning — gate remote flat, manual override needed"),
            job("Lock repair", "Benoni", "Same day", "Shopfront — damaged striker after bump attempt"),
        ],
        "faqs": [
            faq("How fast can someone reach Daveyton from Benoni centre?", "Distance matters — we route the closest available tech."),
            faq("Do you work near Lakefield dams and quieter streets?", "Yes — pin your location for accuracy."),
            faq("Are night rates higher in Crystal Park?", "After-hours fees may apply — ask upfront."),
            faq("Can you help with school-run lockouts near Northmead?", "Yes — morning peaks are common."),
        ],
    },
    {
        "slug": "tembisa",
        "name": "Tembisa",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Tembisa locksmith services",
        "description": "Ivory Park and Tswelopele need locksmiths who communicate clearly and quote before work — we prioritise respectful, transparent service.",
        "suburbs": ["Tembisa", "Ivory Park", "Tswelopele", "Birch Acres"],
        "nearbyAreas": ["Kempton Park", "Midrand", "Edenvale"],
        "recentJobs": [
            job("House lockout", "Tembisa", "23 min response", "Evening — extended family visiting, wrong key grabbed"),
            job("Lock replacement", "Ivory Park", "Same day", "New shack door — padlock upgrade to cylinder"),
            job("Car unlock", "Birch Acres", "18 min response", "Toyota — keys on seat at taxi rank stop"),
        ],
        "faqs": [
            faq("How fast can a locksmith reach Tembisa from Midrand side?", "Depends on traffic on Olifantsfontein — share landmarks."),
            faq("Do you cover Ivory Park informal and formal housing?", "Yes — describe door type when booking."),
            faq("Are night call-outs available in Tembisa?", "Yes — safety first; wait in a lit area if possible."),
            faq("What if I need a cheap fix only?", "Ask for repair-first options where safe."),
        ],
    },
    {
        "slug": "mamelodi",
        "name": "Mamelodi",
        "province": "Gauteng",
        "provinceSlug": "gauteng",
        "tagline": "Mamelodi locksmith services",
        "description": "East of Pretoria, Silverton-adjacent routes and local streets need patient dispatch — we match locksmiths who know the area and quote fairly.",
        "suburbs": ["Mamelodi", "Silverton", "Dennilton", "Mamelodi East"],
        "nearbyAreas": ["Pretoria", "Centurion"],
        "recentJobs": [
            job("House lockout", "Mamelodi", "25 min response", "Late return — padlock key snapped in hasp"),
            job("Lock replacement", "Silverton", "Same day", "Rental handover — full rekey for landlord"),
            job("Car unlock", "Mamelodi East", "20 min response", "Hilux — keys locked while loading furniture"),
        ],
        "faqs": [
            faq("Are locksmith prices higher because Mamelodi is east of Pretoria?", "Distance from the nearest tech can matter — you will see that in the quote."),
            faq("Do you cover Silverton industrial sites?", "Yes — describe roller shutter vs office door."),
            faq("Can you help at night near Mamelodi East?", "Yes — share a safe meeting point."),
            faq("What if I need a child-safe unlock?", "Say so immediately — dispatch prioritises welfare."),
        ],
    },
]

WESTERN_CAPE = [
    {
        "slug": "cape-town",
        "name": "Cape Town",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Cape Town's trusted locksmith service",
        "description": "City Bowl, Atlantic Seaboard and Waterfront traffic mean tight parking and security estates — we route locksmiths who know CBD boom gates and sea-air corrosion on outdoor hardware.",
        "suburbs": ["Cape Town CBD", "Sea Point", "Green Point", "Waterfront", "De Waterkant", "Bo-Kaap", "Gardens", "Tamboerskloof"],
        "nearbyAreas": ["Bellville", "Claremont", "Wynberg", "Observatory"],
        "recentJobs": [
            job("Car lockout", "Sea Point", "13 min response", "Promenade — keys in boot after beach walk"),
            job("House lockout", "Green Point", "16 min response", "Apartment — smart lock battery died at midnight"),
            job("Lock upgrade", "Cape Town CBD", "Same day", "Office suite — master key system partial failure"),
        ],
        "faqs": [
            faq("How much should I expect to pay for a locksmith in Cape Town?", "Seafront humidity and parking hassle can add time. Confirm full scope before drilling."),
            faq("Do you cover Sea Point apartments with strict body corporate rules?", "Yes — mention access codes and basement level."),
            faq("Is the CBD slower during events?", "Sometimes — share if you are near parade routes or stadium events."),
            faq("Can you help with Bo-Kaap heritage doors?", "Often — older hardware may need specialist parts."),
        ],
    },
    {
        "slug": "bellville",
        "name": "Bellville",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Bellville locksmith — northern suburbs",
        "description": "Tygervalley, Parow and Goodwood mix retail intensity with family homes — locksmiths here spend a lot of time in mall basements and complex parking.",
        "suburbs": ["Bellville", "Tygervalley", "Parow", "Goodwood", "Boston", "Oakdale"],
        "nearbyAreas": ["Cape Town", "Brackenfell", "Durbanville"],
        "recentJobs": [
            job("Car unlock", "Tygervalley", "14 min response", "Tyger Valley Centre — SUV keys on seat"),
            job("House lockout", "Bellville", "18 min response", "After work — mortice jammed in older home"),
            job("Lock replacement", "Parow", "Same day", "New deadbolt after attempted break-in"),
        ],
        "faqs": [
            faq("Is Bellville cheaper than Cape Town CBD?", "Often slightly lower attendance, but mall jobs can still take time on site."),
            faq("Do you cover Goodwood and Oakdale flats?", "Yes — describe floor and access."),
            faq("Can you reach Tygervalley Centre quickly?", "Usually — share parking level."),
            faq("Are night call-outs common near Parow retail?", "Yes — especially Friday evenings."),
        ],
    },
    {
        "slug": "stellenbosch",
        "name": "Stellenbosch",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Stellenbosch locksmith — winelands service",
        "description": "Maties-adjacent flats, wine-route guest houses and farm roads need flexible ETAs — we route locksmiths who understand student budgets and estate access.",
        "suburbs": ["Stellenbosch", "Cloetesville", "Kayamandi", "Idas Valley", "Die Boord", "Brandwacht"],
        "nearbyAreas": ["Paarl", "Somerset West", "Franschhoek"],
        "recentJobs": [
            job("House lockout", "Stellenbosch", "20 min response", "Student dig — keys left at res party"),
            job("Car unlock", "Die Boord", "17 min response", "Mall run — remote failed after cold snap"),
            job("Lock repair", "Idas Valley", "Same day", "Farm cottage — old rim lock rusted solid"),
        ],
        "faqs": [
            faq("Do Stellenbosch locksmiths charge more during term time?", "Demand can rise — book early on big event weekends."),
            faq("Can you help on wine farms outside town?", "Often yes — share pin and gate instructions."),
            faq("Are Kayamandi and Cloetesville covered?", "Yes — describe street and landmark."),
            faq("What if I need help after a festival?", "Expect higher traffic — ETAs may stretch."),
        ],
    },
    {
        "slug": "paarl",
        "name": "Paarl",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Paarl locksmith — Berg River Valley",
        "description": "Wellington road links and Huguenot heritage homes mean a mix of agricultural gates and town centre shops — we quote before cutting expensive timber doors.",
        "suburbs": ["Paarl", "Wellington", "Dal Josafat", "Windmeul", "Huguenot"],
        "nearbyAreas": ["Stellenbosch", "Franschhoek", "Worcester"],
        "recentJobs": [
            job("House lockout", "Paarl", "22 min response", "Evening — vineyard worker locked out after shift"),
            job("Lock replacement", "Wellington", "Same day", "Farm gate padlock cut and replaced"),
            job("Car unlock", "Huguenot", "18 min response", "Station pickup — keys in car at platform"),
        ],
        "faqs": [
            faq("Are locksmith prices in Paarl different from Stellenbosch?", "Similar bands — travel to farms can add time."),
            faq("Do you cover Wellington for night emergencies?", "Yes — describe gravel vs tar access."),
            faq("Can you help with winery security after hours?", "Sometimes — commercial access may need extra verification."),
            faq("What if I am locked out on a Berg River smallholding?", "Pin the gate — long driveways affect ETA."),
        ],
    },
    {
        "slug": "worcester",
        "name": "Worcester",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Worcester locksmith — Breede River Valley",
        "description": "Breede Valley retail strips and Avian Park homes need practical fixes — we focus on rust, heat expansion, and honest timelines on the N1 corridor.",
        "suburbs": ["Worcester", "De Bron", "Zwelethemba", "Avian Park", "Roodewal"],
        "nearbyAreas": ["Paarl", "Robertson", "Ceres"],
        "recentJobs": [
            job("Car lockout", "Worcester", "15 min response", "Checkers run — keys locked with engine off"),
            job("House lockout", "De Bron", "19 min response", "Night — security gate stuck halfway"),
            job("Key duplication", "Worcester", "Same day", "Spare keys for elderly parent"),
        ],
        "faqs": [
            faq("How much does a locksmith cost in Worcester vs Cape Town?", "Generally lower metro overhead — confirm parts pricing for imports."),
            faq("Do you cover Avian Park and Zwelethemba?", "Yes — describe door type."),
            faq("Are Sunday call-outs available?", "Yes — retail and travel days create spikes."),
            faq("Can you fix heat-stuck locks after heatwaves?", "Often — sometimes lubrication; sometimes replacement."),
        ],
    },
    {
        "slug": "franschhoek",
        "name": "Franschhoek",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Franschhoek locksmith — Cape Winelands",
        "description": "Guesthouses, wine farms and narrow valley roads mean scenic but slow last-mile access — we set realistic ETAs for tourists and residents alike.",
        "suburbs": ["Franschhoek", "Groendal", "La Motte"],
        "nearbyAreas": ["Stellenbosch", "Paarl"],
        "recentJobs": [
            job("House lockout", "Franschhoek", "25 min response", "Guesthouse — host key left in town"),
            job("Lock replacement", "La Motte", "Same day", "Wine estate office — high-security cylinder"),
            job("Car unlock", "Franschhoek", "22 min response", "Hire car — keys in boot at tasting room"),
        ],
        "faqs": [
            faq("Are Franschhoek call-outs more expensive because of distance?", "Travel time can add to attendance — ask for full quote."),
            faq("Do you serve wine farms with long access roads?", "Yes — share gate codes when allowed."),
            faq("Can tourists get help on public holidays?", "Yes — holidays are peak for guesthouse lockouts."),
            faq("What if I am stuck on a farm road at night?", "Safety first — wait in a visible spot; share pin."),
        ],
    },
    {
        "slug": "somerset-west",
        "name": "Somerset West",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Somerset West locksmith — Helderberg",
        "description": "Somerset Mall, Strand beachfront and Gordon's Bay wind mean salt air on locks and busy summer weekends — we route Helderberg locals who know the strip.",
        "suburbs": ["Somerset West", "Strand", "Gordon's Bay", "Firgrove", "Raithby"],
        "nearbyAreas": ["Cape Town", "Stellenbosch"],
        "recentJobs": [
            job("Car lockout", "Somerset West", "16 min response", "Somerset Mall — keys in car at rooftop"),
            job("House lockout", "Strand", "20 min response", "Beachfront flat — sliding door lock corroded"),
            job("Lock repair", "Gordon's Bay", "Same day", "Salt-air seized gate latch after storm"),
        ],
        "faqs": [
            faq("Do Helderberg locksmiths charge summer surcharges?", "Peak tourism can stretch ETAs — prices follow agreed scope."),
            faq("Can you reach Gordon's Bay harbour area?", "Yes — describe one-way streets and parking."),
            faq("Are Strand holiday lets covered?", "Yes — bring proof if you are managing agent."),
            faq("What if my lock rusted from sea spray?", "Replacement is common — ask for marine-grade options."),
        ],
    },
    {
        "slug": "george",
        "name": "George",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "George locksmith — Garden Route",
        "description": "Garden Route Mall, Pacaltsdorp and coastal humidity mean automotive and gate jobs — we match locksmiths used to slower Garden Route pacing.",
        "suburbs": ["George", "Pacaltsdorp", "Thembalethu", "Loerie Park", "Heather Park"],
        "nearbyAreas": ["Mossel Bay", "Knysna", "Oudtshoorn"],
        "recentJobs": [
            job("Car lockout", "George", "18 min response", "Garden Route Mall — rental keys in boot"),
            job("House lockout", "Loerie Park", "22 min response", "Evening — cylinder failed after humidity"),
            job("Lock replacement", "Pacaltsdorp", "Same day", "Security upgrade after break-in scare"),
        ],
        "faqs": [
            faq("How fast is a locksmith in George compared to Cape Town?", "Fewer traffic jams, but longer distances between suburbs can matter."),
            faq("Do you cover Thembalethu and Pacaltsdorp?", "Yes — describe street and colour of gate."),
            faq("Can you help tourists on the N2 stopover?", "Yes — share accommodation name."),
            faq("Are night rates higher on the Garden Route?", "After-hours fees may apply — confirm first."),
        ],
    },
    {
        "slug": "sea-point",
        "name": "Sea Point",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Sea Point locksmith — Atlantic Seaboard",
        "description": "High-density apartments, promenade foot traffic and Atlantic spray on hardware — we prioritise quiet entry methods where body corporates are strict.",
        "suburbs": ["Sea Point", "Mouille Point", "Three Anchor Bay", "Fresnaye", "Bantry Bay"],
        "nearbyAreas": ["Cape Town CBD", "Green Point", "Camps Bay"],
        "recentJobs": [
            job("House lockout", "Sea Point", "12 min response", "Promenade block — keys inside, baby monitor on"),
            job("Lock upgrade", "Fresnaye", "Same day", "Penthouse — electronic lock intermittent"),
            job("Car unlock", "Mouille Point", "10 min response", "Near lighthouse — tourist rental"),
        ],
        "faqs": [
            faq("Are Sea Point call-outs more expensive than inland?", "Parking and basement access can add minutes — reflected in scope."),
            faq("Do you cover Bantry Bay cliff homes?", "Yes — share security and access notes."),
            faq("Can you work with strict noise rules in blocks?", "We aim for low-damage methods first."),
            faq("What if I am locked out during load-shedding?", "Mention it — electronic locks behave differently."),
        ],
    },
    {
        "slug": "claremont",
        "name": "Claremont",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Claremont locksmith — southern suburbs",
        "description": "Cavendish, Newlands and Rondebosch student pockets mean a mix of high-traffic retail lockouts and Victorian-era doors — we match the right skill to the building.",
        "suburbs": ["Claremont", "Newlands", "Rondebosch", "Kenilworth", "Lansdowne", "Harfield Village"],
        "nearbyAreas": ["Cape Town", "Wynberg", "Constantia"],
        "recentJobs": [
            job("Car lockout", "Claremont", "13 min response", "Cavendish — keys in car at pay station"),
            job("House lockout", "Newlands", "17 min response", "Evening jog — forgot keypad code backup"),
            job("Lock repair", "Rondebosch", "Same day", "Student house — damaged striker after party"),
        ],
        "faqs": [
            faq("Can a locksmith reach UCT-adjacent areas quickly?", "Often yes — traffic on Main Road is the variable."),
            faq("Do Claremont office blocks need after-hours clearance?", "Sometimes — mention building manager contact."),
            faq("Are Victorian doors harder to open without damage?", "Often — say so before drilling is discussed."),
            faq("What does a student budget lockout cost?", "Ask for minimum-invasion options first."),
        ],
    },
    {
        "slug": "tygervalley",
        "name": "Tygervalley",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Tygervalley locksmith — northern suburbs",
        "description": "Willowbridge, Tyger Valley Centre and Panorama homes mean retail basements and hillside estates — we route locksmiths who know the parking levels.",
        "suburbs": ["Tygervalley", "Bellville North", "Panorama", "Welgemoed", "De Tijger"],
        "nearbyAreas": ["Bellville", "Brackenfell", "Durbanville"],
        "recentJobs": [
            job("Car lockout", "Tygervalley", "11 min response", "Willowbridge — keys in boot after shop run"),
            job("Lock replacement", "Panorama", "Same day", "Townhouse — failed smart cylinder"),
            job("House lockout", "Welgemoed", "15 min response", "After shopping — side door deadbolt stuck"),
        ],
        "faqs": [
            faq("Is Tygervalley faster to service than central Bellville?", "Sometimes — closer parking can shorten on-site time."),
            faq("Do you know Willowbridge basement levels?", "Yes — share colour zone and pillar."),
            faq("Can you help with estate intercoms in Welgemoed?", "Often — describe brand if visible."),
            faq("Are night unlocks safe in retail parking?", "Wait near security booths when possible."),
        ],
    },
    {
        "slug": "brackenfell",
        "name": "Brackenfell",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Brackenfell locksmith services",
        "description": "Kuils River sprawl, Kraaifontein access roads and Protea Heights townhouses mean mixed hardware ages — we quote before swapping full multipoint doors.",
        "suburbs": ["Brackenfell", "Kuils River", "Blackheath", "Kraaifontein", "Protea Heights"],
        "nearbyAreas": ["Bellville", "Stellenbosch", "Durbanville"],
        "recentJobs": [
            job("House lockout", "Brackenfell", "18 min response", "Evening — UPVC door multipoint failed"),
            job("Car unlock", "Kuils River", "20 min response", "Workshop yard — keys in bakkie"),
            job("Lock replacement", "Kraaifontein", "Same day", "After break-in — temporary secure then full fit"),
        ],
        "faqs": [
            faq("Do Brackenfell and Kuils River share the same locksmiths?", "Often — we route whoever is closest across the northern belt."),
            faq("Can you reach Kraaifontein during peak N1 traffic?", "ETAs stretch — share alternate routes if known."),
            faq("Are complex homes in Protea Heights covered?", "Yes — mention unit and access."),
            faq("What if I need a weekend gate fix?", "Describe sliding vs swing gate."),
        ],
    },
    {
        "slug": "mitchells-plain",
        "name": "Mitchells Plain",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Mitchells Plain locksmith services",
        "description": "Tafelsig, Westridge and Rocklands need locksmiths who communicate clearly — we emphasise upfront quotes and respectful service on every job.",
        "suburbs": ["Mitchells Plain", "Tafelsig", "Westridge", "Rocklands", "Lentegeur"],
        "nearbyAreas": ["Retreat", "Bellville", "Blue Downs"],
        "recentJobs": [
            job("House lockout", "Mitchells Plain", "22 min response", "Evening — security door chain jammed"),
            job("Lock replacement", "Westridge", "Same day", "New door — cylinder and keys for family"),
            job("Car unlock", "Rocklands", "19 min response", "Toyota — keys inside at school pickup"),
        ],
        "faqs": [
            faq("How fast can someone reach Mitchells Plain from the N2?", "Traffic-dependent — share closest landmark."),
            faq("Do you cover Lentegeur clinic area?", "Yes — describe side street."),
            faq("Are night jobs available in Tafelsig?", "Yes — safety first; wait in lit areas."),
            faq("Can you work with RDP upgrades and extra security?", "Yes — say what is fitted now."),
        ],
    },
    {
        "slug": "durbanville",
        "name": "Durbanville",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Durbanville locksmith services",
        "description": "Wine estates, Pinehurst family estates and Langeberg Ridge views mean long driveways — we set ETAs honestly and quote before climbing access roads.",
        "suburbs": ["Durbanville", "Sonstraal", "Pinehurst", "Vierlanden", "Langeberg Ridge"],
        "nearbyAreas": ["Bellville", "Brackenfell", "Kraaifontein"],
        "recentJobs": [
            job("Car lockout", "Durbanville", "14 min response", "Durbanville Hills — tasting visit, keys in car"),
            job("House lockout", "Pinehurst", "18 min response", "Estate — biometrics flat after power dip"),
            job("Lock upgrade", "Vierlanden", "Same day", "New home — full perimeter rekey"),
        ],
        "faqs": [
            faq("Are Durbanville prices higher because of estate distances?", "Travel time can add — confirm when booking."),
            faq("Do you cover Sonstraal smallholdings?", "Yes — gravel access may slow the van."),
            faq("Can you help with wine-farm-adjacent homes?", "Often — share gate instructions."),
            faq("What if I am locked out on Langeberg Ridge?", "Pin the access road — some are steep."),
        ],
    },
    {
        "slug": "constantia",
        "name": "Constantia",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Constantia locksmith — southern suburbs",
        "description": "Wine estates, Tokai forest edge and Bergvliet family homes mean high-end hardware and long access roads — we match locksmiths comfortable with premium fittings.",
        "suburbs": ["Constantia", "Tokai", "Bergvliet", "Meadowridge", "Kreupelbosch"],
        "nearbyAreas": ["Claremont", "Wynberg", "Hout Bay"],
        "recentJobs": [
            job("House lockout", "Constantia", "16 min response", "Wine estate cottage — heavy timber door"),
            job("Lock upgrade", "Tokai", "Same day", "Smart lock failed — temporary mechanical bypass"),
            job("Safe opening", "Bergvliet", "45 min response", "Inherited safe — combo unknown"),
        ],
        "faqs": [
            faq("Do Constantia jobs cost more because of estate access?", "Premium hardware and long drives can increase time on site."),
            faq("Can you service safes on wine farms?", "Sometimes — proof of ownership may be required."),
            faq("Are Tokai equestrian properties covered?", "Yes — describe gate type."),
            faq("What if my smart lock app failed?", "Mention brand — some have manual override steps."),
        ],
    },
    {
        "slug": "wynberg",
        "name": "Wynberg",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Wynberg locksmith — southern suburbs",
        "description": "Maynard Mall, Plumstead quiet streets and Retreat-adjacent flats mean varied hardware — we route locksmiths who know school-run traffic patterns.",
        "suburbs": ["Wynberg", "Plumstead", "Retreat", "Ottery", "Diep River"],
        "nearbyAreas": ["Claremont", "Constantia", "Mitchells Plain"],
        "recentJobs": [
            job("Car unlock", "Wynberg", "14 min response", "Maynard Mall — keys locked during school shop"),
            job("House lockout", "Plumstead", "17 min response", "Afternoon — latch failed on security gate"),
            job("Lock repair", "Retreat", "Same day", "Old mortice — split after damp season"),
        ],
        "faqs": [
            faq("Can you reach Plumstead faster than Constantia on school days?", "Sometimes — Main Road traffic is the main factor."),
            faq("Do you cover Ottery east of the highway?", "Yes — describe bridge access."),
            faq("Are Retreat flats with multiple locks common?", "Yes — say how many doors are affected."),
            faq("What if I need a child-safe entry?", "Say so immediately for dispatch priority."),
        ],
    },
    {
        "slug": "strand",
        "name": "Strand",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Strand locksmith — Helderberg coast",
        "description": "Beach roads, holiday lets and Macassar wind mean salt on locks and busy summer weekends — we set honest ETAs for locals and visitors.",
        "suburbs": ["Strand", "Gordon's Bay", "Lwandle", "Macassar"],
        "nearbyAreas": ["Somerset West", "Cape Town"],
        "recentJobs": [
            job("House lockout", "Strand", "20 min response", "Holiday let — cleaner left keys inside"),
            job("Car unlock", "Gordon's Bay", "22 min response", "Harbour area — rental with keys in boot"),
            job("Lock replacement", "Macassar", "Same day", "New door after break-in attempt"),
        ],
        "faqs": [
            faq("Are Strand holiday-home lockouts more expensive?", "After-hours and distance to tech can matter — confirm quote."),
            faq("Do you cover Gordon's Bay cliff roads?", "Yes — describe parking."),
            faq("Can tourists get help on long weekends?", "Yes — expect longer ETAs."),
            faq("What if sea spray seized my gate lock?", "Replacement is common — ask for corrosion-resistant options."),
        ],
    },
    {
        "slug": "parow",
        "name": "Parow",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Parow locksmith services",
        "description": "Parow Centre, Goodwood mixed-use and Elsies River access mean dense retail lockouts and older home hardware — we quote before drilling vintage doors.",
        "suburbs": ["Parow", "Goodwood", "Parow North", "Parow Valley", "Elsies River"],
        "nearbyAreas": ["Bellville", "Cape Town", "Tygervalley"],
        "recentJobs": [
            job("Car unlock", "Parow", "15 min response", "Parow Centre — keys on seat after groceries"),
            job("House lockout", "Goodwood", "18 min response", "Evening — security gate stuck halfway"),
            job("Lock replacement", "Elsies River", "Same day", "Burglary repair — temporary board then cylinder"),
        ],
        "faqs": [
            faq("Is Parow cheaper to service than Tygervalley retail?", "Not always — job type matters more than suburb label."),
            faq("Do you cover Elsies River at night?", "Yes — share a safe waiting spot."),
            faq("Can you help with shop shutters near Parow Centre?", "Often — describe roller vs sectional."),
            faq("What if my flat has only one exit door?", "Say so — we prioritise safe entry methods."),
        ],
    },
    {
        "slug": "kuils-river",
        "name": "Kuils River",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Kuils River locksmith services",
        "description": "Blackheath industrial strips, Kleinvlei residential pockets and Mfuleni access mean mixed job types — we route the closest tech across the Kuils sprawl.",
        "suburbs": ["Kuils River", "Blackheath", "Kleinvlei", "Mfuleni"],
        "nearbyAreas": ["Brackenfell", "Stellenbosch", "Blue Downs"],
        "recentJobs": [
            job("House lockout", "Kuils River", "20 min response", "Evening — sliding door off track and locked"),
            job("Car unlock", "Blackheath", "18 min response", "Workshop — fleet van keys inside"),
            job("Lock repair", "Kleinvlei", "Same day", "Damaged padlock hasp after storm"),
        ],
        "faqs": [
            faq("How fast can someone reach Kuils River from Stellenbosch side?", "Depends on R300 traffic — share pin."),
            faq("Do you cover Mfuleni after dark?", "Yes — safety first."),
            faq("Are industrial roller doors covered?", "Often — describe motor vs manual."),
            faq("What if I need the cheapest fix?", "Ask for repair-first scope."),
        ],
    },
    {
        "slug": "retreat",
        "name": "Retreat",
        "province": "Western Cape",
        "provinceSlug": "western-cape",
        "tagline": "Retreat locksmith services",
        "description": "Steenberg, Lavender Hill and Grassy Park blend coastal wind exposure with dense housing — we focus on fair quotes and fast response on the Cape Flats corridor.",
        "suburbs": ["Retreat", "Steenberg", "Lavender Hill", "Grassy Park", "Pelikan Park"],
        "nearbyAreas": ["Wynberg", "Mitchells Plain", "Constantia"],
        "recentJobs": [
            job("House lockout", "Retreat", "19 min response", "Evening — security door multi-lock failed"),
            job("Lock replacement", "Steenberg", "Same day", "New tenants — rekey entire flat"),
            job("Car unlock", "Grassy Park", "22 min response", "Keys inside at takeaway stop"),
        ],
        "faqs": [
            faq("Can a locksmith reach Retreat from the M5 quickly?", "Traffic-dependent — peak hours add minutes."),
            faq("Do you cover Lavender Hill at night?", "Yes — wait in a lit area."),
            faq("Are Pelikan Park homes covered?", "Yes — describe house colour and street."),
            faq("What if I need urgent entry for a child inside?", "Say so immediately — dispatch prioritises."),
        ],
    },
]
# fmt: on


def main() -> None:
    data = {"gauteng": GAUTENG, "westernCape": WESTERN_CAPE}
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(GAUTENG)} Gauteng + {len(WESTERN_CAPE)} WC)")


if __name__ == "__main__":
    main()
