"""Per-city intent bullets for locksmith city pages — geo + behaviour long-tail signals."""

INTENT_BULLETS: dict[str, list[str]] = {
    "johannesburg": [
        "Locked out in Sandton or Rosebank during peak traffic — keys visible in the car at an office park",
        "Lost car keys at Eastgate-area retail or a CBD parking basement",
        "Emergency lock change after a break-in in Melville or Braamfontein",
        "Late-night apartment or student-complex lockout in Auckland Park or Parktown",
    ],
    "sandton": [
        "Estate gate or intercom failure in Bryanston or Morningside",
        "Sandton City or mall basement parking lockout with keys on the seat",
        "Remote or smart key failed after a meeting at a Rivonia office park",
        "After-hours call at a cluster home in Paulshof, Sunninghill or Woodmead",
    ],
    "pretoria": [
        "Hatfield student or shared-flat lockout near campus",
        "Menlyn or Brooklyn retail lockout — keys in the boot after shopping",
        "Government or embassy precinct access delays — cylinder or access card issues",
        "Late-night lockout in Arcadia, Sunnyside or high-density flat blocks",
    ],
    "midrand": [
        "Halfway House or Boulders retail parking — keys locked with kids in the car",
        "Kyalami or Carlswald estate boom gate stuck or visitor pass expired",
        "Office park in Vorna Valley after hours — mortice or glass door fault",
        "Grand Central area — delivery or courier van lockout on the N1 corridor",
    ],
    "centurion": [
        "Irene smallholding or long driveway — padlock or gate motor interlock fault",
        "Lyttelton or Eldoraigne family home — patio slider or security gate jammed",
        "Centurion Mall or strip-mall parking — car unlock without damage",
        "Wierda Park office cottage — after-hours cylinder failure",
    ],
    "randburg": [
        "Ferndale or Northcliff — side gate padlock seized or keys left inside",
        "Cresta or retail strip parking — transponder or remote failure",
        "Townhouse complex shared driveway — intercom-linked deadbolt issues",
        "Early-morning house lockout before school run in Bordeaux or Robindale",
    ],
    "roodepoort": [
        "Florida or Constantia Kloof — rusted gate latch or sliding door off track",
        "Wilgeheuwel shopping run — keys in ignition at undercover parking",
        "Horizon estate — visitor access and cylinder upgrade after attempted break-in",
        "Little Falls ridge roads — ETA-sensitive evening lockout",
    ],
    "soweto": [
        "Diepkloof or Orlando evening return — keys misplaced after taxi or event",
        "Meadowlands or Dobsonville — security door multi-lock or padlock failure",
        "Protea Glen new-build — handover rekey or tenant lock change",
        "Weekend family visit — gate lock or rim cylinder stuck",
    ],
    "boksburg": [
        "East Rand Mall loading zone or basement — retail lockout",
        "Dawn Park shift worker — night mortice or gate failure",
        "Boksburg North industrial roller door or personnel door fault",
        "Benoni-adjacent call — shared East Rand routing from Boksburg",
    ],
    "germiston": [
        "Edenvale near Eastgate — peak traffic car lockout in the mall grid",
        "Bedfordview estate — high-security cylinder after crowbar attempt",
        "Germiston or Primrose — late factory-area lockout",
        "Lambton workshop — fleet van keys locked at the yard",
    ],
    "fourways": [
        "Fourways Mall or Crossing basement — SUV keys on the back seat",
        "Lonehill estate — biometrics flat after load-shedding",
        "Dainfern or Broadacres — intercom fault at the guard house",
        "Chartwell or Douglasdale — after-hours home office lockout",
    ],
    "kempton-park": [
        "OR Tambo rental return or long-stay parking — keys in boot",
        "Birchleigh or Edleen — night shift worker house lockout",
        "Bredell logistics hub — fleet or courier vehicle unlock",
        "Norkem Park — humidity-jammed deadbolt after summer storm",
    ],
    "alberton": [
        "Brackenhurst estate — dogs audible inside, fast entry priority",
        "Alberton City undercover — car keys left during grocery run",
        "Meyersdal ridge — steep driveway access for gate motor issues",
        "Verwoerdpark — rental rekey between tenants",
    ],
    "benoni": [
        "Northmead Square or retail strip — visible keys on the dash",
        "Rynfield Sunday — gate remote flat, manual gate override needed",
        "Daveyton or Crystal Park — evening family lockout",
        "Lakefield or Benoni CBD — shopfront latch after bump attempt",
    ],
    "tembisa": [
        "Ivory Park informal and formal housing — clear address and landmark",
        "Tswelopele — padlock or security gate after hours",
        "Birch Acres — taxi-rank stop car unlock",
        "Late request — wait in a lit area until the tech arrives",
    ],
    "mamelodi": [
        "Mamelodi East — furniture move or bakkie lockout",
        "Silverton handover — landlord full rekey for new tenants",
        "Evening return — snapped key in padlock hasp",
        "Dennilton-linked travel — confirm pin for rural access roads",
    ],
    "cape-town": [
        "Locked out near Sea Point, Green Point or CBD apartments",
        "Airbnb or short-stay guest lock issues — host or guest access",
        "Lost keys during travel or tourism near the V&A Waterfront",
        "Coastal salt spray on balcony sliders, gates or outdoor cylinders",
    ],
    "bellville": [
        "Tygervalley or Willowbridge basement — colour-zone parking lockout",
        "Parow or Goodwood flats — mortice or security gate failure",
        "Boston or Oakdale — older home rim lock after damp season",
        "Northern suburbs retail evening — after-hours shop unlock coordination",
    ],
    "stellenbosch": [
        "Campus-adjacent dig or res — keys left at a social",
        "Die Boord or Idas Valley — wine-route guest house lockout",
        "Kayamandi or Cloetesville — describe street and access",
        "Brandwacht farm road — pin the gate; last mile can be slow",
    ],
    "paarl": [
        "Wellington farm gate — padlock cut and replaced same day",
        "Paarl CBD shop — roller shutter or glass door fault",
        "Huguenot or Windmeul — heritage door hardware specialist needed",
        "Dal Josafat industrial — workshop or yard lockout",
    ],
    "worcester": [
        "Breede Valley retail — Checkers or mall run car lockout",
        "De Bron or Zwelethemba — security gate stuck halfway",
        "Avian Park — describe door type for correct tools",
        "Heatwave expansion — sticky deadbolt on exterior doors",
    ],
    "franschhoek": [
        "Guesthouse host key left in town — tourist lockout",
        "La Motte or estate road — hire car keys in boot at tasting",
        "Narrow valley traffic — realistic ETA for wine-farm access",
        "Night-time farm road — safety-first; share WhatsApp pin",
    ],
    "somerset-west": [
        "Somerset Mall rooftop — weekend retail car lockout",
        "Strand beachfront flat — sliding door lock corroded by sea spray",
        "Gordon’s Bay harbour area — one-way streets and tight parking",
        "Firgrove or Raithby — family home cylinder after storm wind damage",
    ],
    "george": [
        "Garden Route Mall rental — keys in boot after coastal drive",
        "Loerie Park — humidity cylinder failure",
        "Pacaltsdorp or Thembalethu — confirm landmark for routing",
        "Heather Park — new home perimeter rekey after move-in",
    ],
    "sea-point": [
        "Promenade block — baby monitor on, fast non-destructive entry",
        "Mouille Point or Three Anchor Bay — tourist rental lockout",
        "Fresnaye or Bantry Bay — penthouse electronic lock intermittent",
        "Load-shedding — smart lock app failed; manual override needed",
    ],
    "claremont": [
        "Cavendish parking pay station — keys locked in car",
        "Newlands or Rondebosch student house — damaged striker after event",
        "Kenilworth or Lansdowne — shared entrance flats",
        "UCT-adjacent — weekday traffic affects ETA on Main Road",
    ],
    "tygervalley": [
        "Willowbridge colour zone — basement find for faster unlock",
        "Panorama townhouse — failed smart cylinder",
        "Welgemoed estate — intercom brand and error code if known",
        "Bellville North retail evening — wait near security booth",
    ],
    "brackenfell": [
        "Kuils River — UPVC multipoint door failure",
        "Blackheath workshop — fleet bakkie keys inside",
        "Kraaifontein — attempted break-in; temporary secure then full repair",
        "Protea Heights — sectional-title rekey",
    ],
    "mitchells-plain": [
        "Tafelsig or Westridge — security door chain jammed",
        "Rocklands school run — keys inside at takeaway",
        "Lentegeur clinic area — describe side street",
        "Evening call — wait in a lit, visible spot",
    ],
    "durbanville": [
        "Durbanville Hills or wine route — tasting visit car lockout",
        "Pinehurst estate — biometrics flat after power dip",
        "Vierlanden new estate — full perimeter rekey",
        "Sonstraal smallholding — gravel access may add minutes",
    ],
    "constantia": [
        "Tokai equestrian or smallholding — gate type matters",
        "Wine estate cottage — heavy timber door hardware",
        "Bergvliet family home — safe opening with proof of ownership",
        "Meadowridge — smart lock brand for correct override steps",
    ],
    "wynberg": [
        "Maynard Mall school-week shop — car lockout",
        "Plumstead — security gate latch failed in damp season",
        "Retreat or Ottery flats — multiple locks on one visit",
        "Diep River — child inside; say so for dispatch priority",
    ],
    "strand": [
        "Holiday let cleaner locked out — spare key inside",
        "Gordon’s Bay rental — keys in boot near harbour",
        "Lwandle or Macassar — new door after break-in attempt",
        "Long weekend — expect longer ETAs on coastal roads",
    ],
    "parow": [
        "Parow Centre groceries — keys on seat after shop run",
        "Goodwood evening — security gate halfway stuck",
        "Elsies River — burglary repair board then cylinder",
        "Parow North — single exit flat; non-destructive entry first",
    ],
    "kuils-river": [
        "Kuils River sliding door — off track and locked",
        "Blackheath yard — fleet van lockout",
        "Kleinvlei — padlock hasp after wind damage",
        "Mfuleni — night safety; lit waiting point",
    ],
    "retreat": [
        "Steenberg new tenants — full flat rekey",
        "Lavender Hill — evening security door failure",
        "Grassy Park takeaway — keys inside at collection",
        "Pelikan Park — child welfare urgent entry; say so immediately",
    ],
}
